<a href="https://colab.research.google.com/github/suneethrast-lang/Python_Suneethra/blob/main/Panda_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd

In [33]:
s=pd.Series([1,2,3,4,5,6,7])
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [34]:
index_day=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
data=[1,2,3,4,5,6,7]
print

In [35]:
s=pd.Series(data,index=index_day) #First value=Data, Second value=Index value
s

Monday       1
Tuesday      2
Wednesday    3
Thursday     4
Friday       5
Saturday     6
Sunday       7
dtype: int64

In [36]:
s.mean()

np.float64(4.0)

In [37]:
#Data frame-->To put it into a table of things
df=pd.DataFrame({'First':s,'Second':s*2,'Third':s*5,'Fourth':s*s})
df

           First  Second  Third  Fourth
Monday         1       2      5       1
Tuesday        2       4     10       4
Wednesday      3       6     15       9
Thursday       4       8     20      16
Friday         5      10     25      25
Saturday       6      12     30      36
Sunday         7      14     35      49

In [38]:
s*3

Monday        3
Tuesday       6
Wednesday     9
Thursday     12
Friday       15
Saturday     18
Sunday       21
dtype: int64

In [39]:
#Way-01
column_names=['City','Popluation','Language']
index_country=['Japan','India','China','Brazil','Mexico']

In [40]:
row1=['Tokyo',37.4,'Japanese']
row2=['Delhi',28.5,'Hindi']
row3=['Shanghai',27.5,'Mandarin']
row4=['San Pailo',21.5,'Spanish']
row5=['Mexico city',21.6,'Spanish']
data=[row1,row2,row3,row4,row5]

In [41]:
df=pd.DataFrame(data,index=index_country,columns=column_names)
df

               City  Popluation  Language
Japan         Tokyo        37.4  Japanese
India         Delhi        28.5     Hindi
China      Shanghai        27.5  Mandarin
Brazil    San Pailo        21.5   Spanish
Mexico  Mexico city        21.6   Spanish

In [42]:
#Way-02
Cities=['Tokyo','Mumbai','Shanghai','Rio','Mexico city']
Popluation=[37.4,28.5,27.5,21.5,21.6]
Popu_dict={'City':Cities,'Popluation':Popluation}

In [43]:
df=pd.DataFrame(Popu_dict,index=index_country)
df

               City  Popluation
Japan         Tokyo        37.4
India        Mumbai        28.5
China      Shanghai        27.5
Brazil          Rio        21.5
Mexico  Mexico city        21.6